import { tokenNames, getToken } from './tokens.js';
import { DEFAULT_TOKENS, mergeTokens } from './render/tokens.js';

// Tokens in the shapes a developer drops into a codebase. `css` is the same custom properties
// the viewer runs on — `:root` for the default context and one `[data-theme="<ctx>"]` block per
// other context, holding only what differs; `tailwind` is a `theme.extend` object grouped by
// what the token names say (color.*, space.*, radius.*, font.*). Neither invents a value: both
// are readings of the resolved set (DESIGN.md §6.10).

const cssName = (name) => `--${name.replace(/\./g, '-')}`;

export function tokensCss(project) {
  const set = project.tokenSet ?? {};
  const merged = mergeTokens(DEFAULT_TOKENS, project.tokens);
  const names = tokenNames(merged);
  const lines = [':root {', ...names.map((n) => `  ${cssName(n)}: ${getToken(merged, n)};`), '}'];
  for (const [axis, byCtx] of Object.entries(set.contexts ?? {})) {
    const def = set.defaults?.[axis];
    for (const [ctx, tokens] of Object.entries(byCtx)) {
      if (ctx === def) continue;
      const diff = names.filter((n) => getToken(tokens, n) !== undefined && getToken(tokens, n) !== getToken(merged, n));
      if (!diff.length) continue;
      lines.push('', `/* ${axis}: ${ctx} */`, `[data-theme="${ctx}"] {`, ...diff.map((n) => `  ${cssName(n)}: ${getToken(tokens, n)};`), '}');
    }
  }
  return lines.join('\n') + '\n';
}

const GROUPS = { color: 'colors', space: 'spacing', radius: 'borderRadius', shadow: 'boxShadow', control: 'minHeight', font: 'font' };

export function tokensTailwind(project) {
  const merged = mergeTokens(DEFAULT_TOKENS, project.tokens);
  const extend = {};
  for (const name of tokenNames(merged)) {
    const [group, ...rest] = name.split('.');
    const value = getToken(merged, name);
    const key = rest.join('-') || 'DEFAULT';
    if (group === 'font') {
      if (rest[0] === 'family') (extend.fontFamily ??= {})[rest.slice(1).join('-') || 'sans'] = String(value).split(',').map((s) => s.trim());
      else if (rest[0] === 'size') (extend.fontSize ??= {})[rest.slice(1).join('-') || 'base'] = value;
      else if (rest[0] === 'weight') (extend.fontWeight ??= {})[rest.slice(1).join('-') || 'DEFAULT'] = value;
      else (extend[`font-${rest[0]}`] ??= {})[rest.slice(1).join('-') || 'DEFAULT'] = value;
      continue;
    }
    const bucket = GROUPS[group] ?? group;
    (extend[bucket] ??= {})[key] = value;
  }
  return `// generated by doan from the resolved token set — do not edit, change tokens/ instead\nmodule.exports = { theme: { extend: ${JSON.stringify(extend, null, 2)} } };\n`;
}
